# Generated by Django 4.2.19 on 2026-04-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='google, bing, yahoo, duckduckgo', max_length=50, unique=True)),
                ('base_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_label', models.CharField(max_length=10)),
                ('group_range', models.CharField(max_length=10)),
                ('search_term', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchFilter.searchengine')),
                ('search_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchFilter.searchterm')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ad_promo', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchFilter.searchrun')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_data', models.TextField(blank=True, null=True)),
                ('term_frequency', models.IntegerField(default=0)),
                ('scrape_timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='searchFilter.searchresult')),
            ],
        ),
    ]
